name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.9"
          channels: conda-forge
          activate-environment: myrootenv

      - name: Create env and install ROOT (includes pythia8)
        shell: bash -l {0}
        run: |
          conda create -y -n myrootenv python=3.9 -c conda-forge
          conda activate myrootenv
          conda install -y -c conda-forge root
          python - <<'PY'
          import ROOT
          print("ROOT OK")
          import pythia8
          print("Pythia8 OK")
          PY

      - name: Install Python deps via pip (torch + package deps from pyproject)
        shell: bash -l {0}
        run: |
          conda activate myrootenv
          python -m pip install --upgrade pip
          # Torch CPU wheels
          pip install -e .

      - name: Configure headless Matplotlib
        shell: bash -l {0}
        run: |
          echo "MPLBACKEND=Agg" >> $GITHUB_ENV

      - name: Run unit tests
        shell: bash -l {0}
        run: |
          conda activate myrootenv
          python -m unittest discover -s tests -p "test_*.py" -v

